networks:
  dagster_network:
    driver: bridge

services:
  dagster-postgres:
    image: postgres:15-alpine
    container_name: dagster-postgres
    ports:
      - 5432:5432
    networks:
      - dagster_network
    restart: unless-stopped
    environment:
      POSTGRES_USER: dagster
      POSTGRES_PASSWORD: dagster
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dagster" ]

  minio:
    image: minio/minio:latest
    container_name: dagster-minio
    networks:
      - dagster_network
    restart: unless-stopped
    command: ["server", "/data", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: dagsterapp
      MINIO_ROOT_PASSWORD: dagsterapp
    volumes:
      - ./data/s3_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9000/minio/health/live || exit 1"]