[project]
name = "dagster-nomad-demo"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.11"

dependencies = [
    "dagster-aws~=0.29.13",
    "dagster~=1.13.13",
    "dagster-postgres~=0.29.13",
    "dagster-webserver~=1.13.13",
    "httpx2~=2.9.1",
    "dagster-nomad",
]

[tool.ruff]
line-length = 120
exclude = [
    ".direnv",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "__pypackages__",
    "build",
    "dist",
    "venv",
]

[tool.uv.workspace]
members = ["dagster-nomad"]

[tool.uv.sources]
dagster-nomad = { workspace = true }

[dependency-groups]
dev = [
    "pandas>=2.2.3",
    "pytest>=9.1.1",
    "rich>=14.0.0",
    "ruff>=0.11.6",
]
